email = "fabletang@outlook.com"
#facebook = "facebookusername"
github = "fabletang"
#gitlab = "gitlabusername"
#linkedin = "linkedinusername"
#stackoverflow = "stackoverflowuserid"
#twitter = "twitterusername"
#weibo = "weibousername"
#zhihu = "zhihuusername"
#instagram = "instagramusername"
#quora = "quorausername"
#tumblr = "tumblrusername"
#reddit = "redditusername"
#telegram = "telegramusername"
#qq = "qqnumber"
#dockerhub = "dockerhubusername"
#bitbucket = "bitbucketworkspaceid"
